# Generated by Django 5.1.1 on 2024-10-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frends',
            name='settings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
