# Generated by Django 5.1.1 on 2024-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mediatype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
