# Generated by Django 5.1.1 on 2024-10-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mediatype',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
