# Generated by Django 5.1.1 on 2024-11-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_mediatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_number1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_number2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
