# Generated by Django 5.1.1 on 2024-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_available_days_service_contact_number1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='end_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
