# Generated by Django 5.1.1 on 2024-10-22 06:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('ocord', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('media', models.TextField(blank=True, null=True)),
                ('mediatype', models.CharField(blank=True, max_length=255, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('comments', models.JSONField(blank=True, default=list, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
