# Generated by Django 5.1.1 on 2024-11-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='disliked_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='feed',
            name='liked_by',
            field=models.JSONField(default=list),
        ),
    ]
