# Generated by Django 5.1.1 on 2025-01-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_disliked_by_feed_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='typeofcontent',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
