# Generated by Django 5.1.1 on 2024-10-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_bucketlist_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
