# Generated by Django 5.1.1 on 2025-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0003_bucketlist_end_date_bucketlist_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='visble',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
