# Generated by Django 5.1.1 on 2024-11-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_customuser_ocoord_customuser_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ocoord',
            new_name='ocord',
        ),
    ]
